### ISSUE TITLE
add this repository to TSS team

### ISSUE THREAD

**Issue by stephf0716** [rij805/ATEF_Timing#3]
You can add the repository to TSS team here: https://github.com/orgs/slaclab/teams/tss/repositories
Set the permission level to "Maintain" so the rest of the team can be able to manage the repository.

**Comment by rij805** [comment]
https://confluence.slac.stanford.edu/display/timing/ATEF+Timing+Checkout This is the new link to the repo, and TSS has maintain privileges there.
